# Ustal minimalną wersję iOS wymaganą przez pluginy (np. mobile_scanner)
platform :ios, '15.5'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  # Wymuś architekturę arm64 dla symulatora na Apple Silicon i ustaw iOS 15.5
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
    config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['DEFINES_MODULE'] = 'YES'
      
      # Wymuszaj Swift 5.0 dla wszystkich podów
      if !config.build_settings['SWIFT_VERSION'] || config.build_settings['SWIFT_VERSION'].empty?
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
      
      # Wyłącz bitcode i module interface
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['SWIFT_EMIT_MODULE_INTERFACE'] = 'NO'
      
      # Wyłącz ostrzeżenia o przestarzałych API w zewnętrznych bibliotekach
      config.build_settings['GCC_WARN_DEPRECATED_FUNCTIONS'] = 'NO'
    end
    flutter_additional_ios_build_settings(target)
  end
end
